// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blog/blog.proto

package pbblog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	user "user"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Blog struct {
	Title                string     `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string     `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	User                 *user.User `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Blog) Reset()         { *m = Blog{} }
func (m *Blog) String() string { return proto.CompactTextString(m) }
func (*Blog) ProtoMessage()    {}
func (*Blog) Descriptor() ([]byte, []int) {
	return fileDescriptor_e737bdbda5671783, []int{0}
}

func (m *Blog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog.Unmarshal(m, b)
}
func (m *Blog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog.Marshal(b, m, deterministic)
}
func (m *Blog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog.Merge(m, src)
}
func (m *Blog) XXX_Size() int {
	return xxx_messageInfo_Blog.Size(m)
}
func (m *Blog) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog.DiscardUnknown(m)
}

var xxx_messageInfo_Blog proto.InternalMessageInfo

func (m *Blog) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Blog) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Blog) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*Blog)(nil), "pb.blog.Blog")
}

func init() { proto.RegisterFile("blog/blog.proto", fileDescriptor_e737bdbda5671783) }

var fileDescriptor_e737bdbda5671783 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xca, 0xc9, 0x4f,
	0xd7, 0x07, 0x11, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x05, 0x49, 0x7a, 0x20, 0xae,
	0x14, 0x7f, 0x69, 0x71, 0x6a, 0x91, 0x3e, 0x88, 0x80, 0xc8, 0x28, 0x05, 0x73, 0xb1, 0x38, 0xe5,
	0xe4, 0xa7, 0x0b, 0x89, 0x70, 0xb1, 0x96, 0x64, 0x96, 0xe4, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0x41, 0x38, 0x42, 0x42, 0x5c, 0x2c, 0x49, 0xf9, 0x29, 0x95, 0x12, 0x4c, 0x60, 0x41,
	0x30, 0x5b, 0x48, 0x91, 0x8b, 0x05, 0xa4, 0x5f, 0x82, 0x59, 0x81, 0x51, 0x83, 0xdb, 0x88, 0x57,
	0xaf, 0x20, 0x49, 0x0f, 0x6c, 0x5e, 0x68, 0x71, 0x6a, 0x51, 0x10, 0x58, 0xca, 0x89, 0x23, 0x8a,
	0xad, 0x20, 0x09, 0x64, 0x5f, 0x12, 0x1b, 0xd8, 0x16, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x4c, 0x78, 0x49, 0x3b, 0x92, 0x00, 0x00, 0x00,
}
